### ISSUE TITLE
Year type

### ISSUE THREAD

**Issue by pvdbosch** [belgif/openapi-time#1]
validate Year type in time-v1beta.yaml

OK (integer-based) for rest design WG, last validation by functional WG

If OK, move to v1.

**Comment by pvdbosch** [comment]
approved by functional WG. Year promoted to v1.

**Comment by smals-chlo** [comment]
Hi @pvdbosch , @jpraet 
We are wondering why the  YearQuarter was choosen to be like this: 
 
> YearQuarter:
>     type: string
>     pattern: '^[0-9]{4}Q(1|2|3|4)$'
>     description: '[quarter in a Gregorian Calendar Year](https://en.wikipedia.org/wiki/Calendar_year#Quarters) with the year included'
>     example: '2020Q1'

At Smals it is usually a 5 digit integer (YYYYQ).
Is the decision based on a standard? 
In wikipedia, I find no mention about the format.

**Comment by pvdbosch** [comment]
I don't think there's a standard, but the most common used abbreviation for quarter is Q1, Q2, Q3, and Q4 (like in the linked wikipedia article). Then using the letter Q as separator seems logical, and is more readable.

YearMonth uses a separator as well, e.g. "2020-02" and 5 digits just reads like a single big number.
